# basic options
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: kitian616/jekyll-TeXt-theme

#Color
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
