# basic options
title: NEOCONOMIX
author: TITO
email: your-email@domain.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  MASR27

# Build settings
markdown: #
remote_theme: kitian616/jekyll-TeXt-theme

#Color
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
#highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"

