


# basic options
title: DDL
author: GitHub User
email: your-email@domain.com
description: A wonderful site
twitter_username: MEXDATA
github_username:  MASR27

# Build settings
markdown: kramdown
theme: jekyll-text-theme 

## => Site Settings
##############################
text_skin: dark # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
